name: Test        
    
on:
  issue_comment:
    types: [created]
    
jobs:
  retest:        
    name: Re-Test     
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.issue.number }}
      REPO: ${{ github.repository }}
      SHA_REF: ${{ github.event.issue.pull_request.head.ref }}
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/retest')
    permissions:
      actions: write
    steps:
      - name: Re-run failed jobs for this PR
        run: |
          RUN_ID=$(gh api "repos/$REPO/actions/workflows/test.yml/runs?per_page=1&event=pull_request&head_sha=$SHA_REF" | jq -r '.workflow_runs[] | .id')
          gh api --method POST repos/$REPO/actions/runs/$RUN_ID/rerun-failed-jobs
