name: Test        
    
on:
  issue_comment:
    types: [created]
  pull_request_review:
    
jobs:
  retest:        
    name: Re-Test     
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.issue.number }}
      REPO: ${{ github.repository }}
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/retest') || github.event.review.state == 'approved'
    permissions:
      actions: write
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Re-run failed jobs for this PR
        run: |
          SHA_REF=$(curl -H "Accept: application/vnd.github+json" \
                        -H "Authorization: Bearer $GH_TOKEN" \
                        "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/commits" | jq -r '.[].sha' | tail -n 1)
          echo $SHA_REF
          RUN_ID=$(curl -H "Accept: application/vnd.github+json" \
                        -H "Authorization: Bearer $GH_TOKEN" \
                        "https://api.github.com/repos/$REPO/actions/workflows/test.yml/runs?per_page=1&event=pull_request&head_sha=$SHA_REF" | jq -r '.workflow_runs[] | .id')
          curl -X POST \
               -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer $GH_TOKEN" \
               "https://api.github.com/repos/$REPO/actions/runs/$RUN_ID/rerun-failed-jobs"
