name: Test        
    
on:
  issue_comment:
    
jobs:
  test:        
    name: Test     
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.issue.number }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
