name: Test        
    
on:
  pull_request:
  issue_comment:
    
jobs:
  test:        
    name: Test     
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master' || github.event.issue.pull_request
    env:
      PR_NUMBER: ${{ github.event.issue.number || github.event.number }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
