name: Test        
    
on:
  pull_request:
  pull_request_review:
    
jobs:
  test:        
    name: Test     
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    env:
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Fail Job
        run: exit 1
